# Generated by Django 6.1.1 on 2026-09-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='customer', max_length=50),
        ),
    ]
