# Generated by Django 6.1.1 on 2026-09-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('working_hours', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
