# Generated by Django 6.1.1 on 2026-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_alter_profile_description_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
